[theme]
base = "light"
primaryColor = "#4F46E5"
backgroundColor = "#F7F7F9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
